/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormAturan.java
 *
 *  
 */
package dmfuzzytsukamoto;

import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Fiqih Amrullah
 */
public class FormAturan extends javax.swing.JDialog {
     List<Aturan> listaturan;
     List<Variable> listvariable;
     List<Himpunan> listhimpunan;
     List<Himpunan> listdetailaturan;
     int idxrow;
     int idxrow2;
    /** Creates new form FormAturan */
    public FormAturan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Util.TengahWindow(this);
        loadDataAturan();
        fillDataComboVariable();
    }
    
     public void fillDataComboVariable()
    {
        DataProcessor dp = new DataProcessor();
        listvariable = dp.loadListVariable();
        for(int i=0;i<listvariable.size();i++) 
        {
            jCmbVariable.addItem(listvariable.get(i).getNmVar());
        }
    }
     
       public void fillDataComboHimpunan(int idvar)
    {
        DataProcessor dp = new DataProcessor();
        jCmbHimpunan.removeAllItems();
        listhimpunan = dp.loadListHimpunan(idvar);
        for(int i=0;i<listhimpunan.size();i++) 
        {
            jCmbHimpunan.addItem(listhimpunan.get(i).getNmhimp());
        }
    }

    public void loadDataAturan()
    {
        DataProcessor dp = new DataProcessor();
        listaturan = dp.loadListAturan();
        String header[] = new String[] {"No","No Aturan","Keputusan(Consequent)"};
        jTblAturan.setModel(TableViewer.ConvertAturanListToTableModel(listaturan, header));
    }
    
    public void loadDetailAturan(String noaturan)
    {
        DataProcessor dp = new DataProcessor();
        listdetailaturan = dp.loadDetailListAturan(noaturan);
        String header[] = new String[] {"No","Nama Variabel","Himpunan"};
        jTblDetailAturan.setModel(TableViewer.ConvertDetailAturanListToTableModel(listdetailaturan,header));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblAturan = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTxtNoAturan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jCmbResikoDM = new javax.swing.JComboBox();
        jBtnTambahAturan = new javax.swing.JButton();
        jBtnHapusAturan = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jCmbVariable = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jCmbHimpunan = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTblDetailAturan = new javax.swing.JTable();
        jBtnTutup = new javax.swing.JButton();
        jBtnTambahDetailAturan = new javax.swing.JButton();
        jBtnHapusDetailAturan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kelola Aturan (Rule Base)");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setText("ATURAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 110));

        jTblAturan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTblAturan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblAturanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTblAturan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 303, 337, 250));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Entri Aturan"));

        jLabel2.setText("No Aturan:");

        jLabel3.setText("Resiko DM:");

        jCmbResikoDM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sangat Rendah", "Rendah", "Sedang", "Tinggi", "Sangat Tinggi" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTxtNoAturan, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCmbResikoDM, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel3)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtNoAturan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCmbResikoDM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 131, -1, 100));

        jBtnTambahAturan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gbr/plus_16.png"))); // NOI18N
        jBtnTambahAturan.setText("Tambah");
        jBtnTambahAturan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTambahAturanActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnTambahAturan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 96, 35));

        jBtnHapusAturan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gbr/trash_16.png"))); // NOI18N
        jBtnHapusAturan.setText("Hapus");
        jBtnHapusAturan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnHapusAturanActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnHapusAturan, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 99, 35));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail Aturan"));

        jLabel4.setText("Variable:");

        jCmbVariable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbVariableActionPerformed(evt);
            }
        });

        jLabel5.setText("Himpunan:");

        jCmbHimpunan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbHimpunanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCmbVariable, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 188, Short.MAX_VALUE))
                    .addComponent(jCmbHimpunan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCmbVariable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCmbHimpunan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 131, 270, -1));

        jTblDetailAturan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTblDetailAturan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblDetailAturanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTblDetailAturan);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 303, 430, 250));

        jBtnTutup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gbr/exit.png"))); // NOI18N
        jBtnTutup.setText("Tutup");
        jBtnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTutupActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnTutup, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 560, 120, 47));

        jBtnTambahDetailAturan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gbr/plus_16.png"))); // NOI18N
        jBtnTambahDetailAturan.setText("Tambah");
        jBtnTambahDetailAturan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTambahDetailAturanActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnTambahDetailAturan, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 140, 120, 36));

        jBtnHapusDetailAturan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gbr/trash_16.png"))); // NOI18N
        jBtnHapusDetailAturan.setText("Hapus");
        jBtnHapusDetailAturan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnHapusDetailAturanActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnHapusDetailAturan, new org.netbeans.lib.awtextra.AbsoluteConstraints(669, 180, 120, 36));

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jBtnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTutupActionPerformed
// TODO add your handling code here:
    this.dispose();
}//GEN-LAST:event_jBtnTutupActionPerformed

private void jBtnTambahAturanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTambahAturanActionPerformed
// TODO add your handling code here:
    Aturan aturan = new Aturan();
    aturan.setNoAturan(jTxtNoAturan.getText());
    aturan.setKep(jCmbResikoDM.getSelectedIndex());
    DataProcessor dp = new DataProcessor();
    dp.SimpanAturan(aturan);
    loadDataAturan();
    JOptionPane.showMessageDialog(this, "Data Aturan Berhasil Disimpan!","Sukses",JOptionPane.INFORMATION_MESSAGE);
}//GEN-LAST:event_jBtnTambahAturanActionPerformed

private void jBtnHapusAturanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnHapusAturanActionPerformed
// TODO add your handling code here:
    int respon = JOptionPane.showConfirmDialog(this,"Apakah Anda yakin akan menghapus aturan tersebut?","Konfirmasi",JOptionPane.YES_NO_OPTION);
    if (respon == JOptionPane.YES_NO_OPTION)
    {
        DataProcessor dp = new DataProcessor();
        dp.HapusAturan(listaturan.get(idxrow));
        loadDataAturan();
        JOptionPane.showMessageDialog(this, "Data Aturan Berhasil Dihapus!","Sukses",JOptionPane.INFORMATION_MESSAGE);
    }
}//GEN-LAST:event_jBtnHapusAturanActionPerformed

private void jTblAturanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblAturanMouseClicked
// TODO add your handling code here:
    idxrow  = jTblAturan.rowAtPoint(evt.getPoint());
    loadDetailAturan(listaturan.get(idxrow).getNoAturan());
}//GEN-LAST:event_jTblAturanMouseClicked

private void jCmbHimpunanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbHimpunanActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jCmbHimpunanActionPerformed

private void jCmbVariableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbVariableActionPerformed
// TODO add your handling code here:
    fillDataComboHimpunan(listvariable.get(jCmbVariable.getSelectedIndex()).getIdVar());
}//GEN-LAST:event_jCmbVariableActionPerformed

private void jBtnTambahDetailAturanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTambahDetailAturanActionPerformed
// TODO add your handling code here:
    Aturan aturan = new Aturan();
    aturan.setNoAturan(listaturan.get(idxrow).getNoAturan());
    Himpunan himp = new Himpunan();
    himp.getVar().setIdVar(listvariable.get(jCmbVariable.getSelectedIndex()).getIdVar());
    himp.setIdHimp(listhimpunan.get(jCmbHimpunan.getSelectedIndex()).getIdHimp());
    DataProcessor dp = new DataProcessor();
    dp.SimpanAntecedent(aturan, himp);
    loadDetailAturan(listaturan.get(idxrow).getNoAturan());
    JOptionPane.showMessageDialog(this, "Data Detail Aturan(Anteseden) Berhasil Disimpan!","Sukses",JOptionPane.INFORMATION_MESSAGE);
}//GEN-LAST:event_jBtnTambahDetailAturanActionPerformed

private void jBtnHapusDetailAturanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnHapusDetailAturanActionPerformed
// TODO add your handling code here:
    int respon = JOptionPane.showConfirmDialog(this,"Apakah Anda yakin akan menghapus Detail Aturan tersebut?","Konfirmasi",JOptionPane.YES_NO_OPTION);
    if (respon == JOptionPane.YES_NO_OPTION)
    {
        DataProcessor dp = new DataProcessor();
        dp.HapusAntecedent(listdetailaturan.get(idxrow2).getVar().getIdVar(),listdetailaturan.get(idxrow2).getIdHimp(),listaturan.get(idxrow).getNoAturan());
        loadDetailAturan(listaturan.get(idxrow).getNoAturan());
        JOptionPane.showMessageDialog(this, "Data Detail Aturan Berhasil Dihapus!","Sukses",JOptionPane.INFORMATION_MESSAGE);
    }
}//GEN-LAST:event_jBtnHapusDetailAturanActionPerformed

private void jTblDetailAturanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblDetailAturanMouseClicked
// TODO add your handling code here:
    idxrow2 = jTblDetailAturan.rowAtPoint(evt.getPoint());
}//GEN-LAST:event_jTblDetailAturanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAturan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAturan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAturan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAturan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                FormAturan dialog = new FormAturan(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnHapusAturan;
    private javax.swing.JButton jBtnHapusDetailAturan;
    private javax.swing.JButton jBtnTambahAturan;
    private javax.swing.JButton jBtnTambahDetailAturan;
    private javax.swing.JButton jBtnTutup;
    private javax.swing.JComboBox jCmbHimpunan;
    private javax.swing.JComboBox jCmbResikoDM;
    private javax.swing.JComboBox jCmbVariable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTblAturan;
    private javax.swing.JTable jTblDetailAturan;
    private javax.swing.JTextField jTxtNoAturan;
    // End of variables declaration//GEN-END:variables
}
